"""Shared response schemas for kr-gov-job-mcp."""

from kr_gov_job_mcp.schemas.alio import (
    AlioInstitution,
    AlioInstitutionSearchResult,
    AlioPointAttachment,
    AlioPointItem,
    AlioPointKind,
    AlioPointSearchResult,
    AlioReportDisclosure,
    AlioReportFile,
    AlioReportSearchResult,
)
from kr_gov_job_mcp.schemas.cleaneye import (
    CleaneyeDisclosureItem,
    CleaneyeInstitution,
    CleaneyeInstitutionKind,
    CleaneyeInstitutionSearchResult,
)
from kr_gov_job_mcp.schemas.job import (
    JobAlioAttachment,
    JobAlioDetail,
    JobAlioSearchResult,
    JobAlioStep,
    JobAlioSummary,
)
from kr_gov_job_mcp.schemas.job_fit import (
    ApplicantReadinessInput,
    InstitutionMaterialCheck,
    JobFitEvidenceSource,
    JobFitEvidenceType,
    JobFitInstitutionSignal,
    JobFitPreparationItem,
    JobFitPreparationReport,
    JobFitVerificationNote,
    PreparationPriority,
)
from kr_gov_job_mcp.schemas.ncs import (
    KsaCandidate,
    KsaCategory,
    NcsAttachmentCandidate,
    NcsCodeMapping,
    NcsEvidenceReference,
    NcsEvidenceType,
    NcsMappingInput,
    NcsVerificationNote,
)
from kr_gov_job_mcp.schemas.institution import (
    InstitutionAnalysisInput,
    InstitutionEvidence,
    InstitutionIdentityCandidate,
    InstitutionSignalCandidate,
    InstitutionSignalCategory,
    InstitutionSourceType,
    InstitutionVerificationNote,
)

__all__ = [
    "AlioInstitution",
    "AlioInstitutionSearchResult",
    "AlioPointAttachment",
    "AlioPointItem",
    "AlioPointKind",
    "AlioPointSearchResult",
    "AlioReportDisclosure",
    "AlioReportFile",
    "AlioReportSearchResult",
    "CleaneyeDisclosureItem",
    "CleaneyeInstitution",
    "CleaneyeInstitutionKind",
    "CleaneyeInstitutionSearchResult",
    "ApplicantReadinessInput",
    "InstitutionMaterialCheck",
    "InstitutionAnalysisInput",
    "InstitutionEvidence",
    "InstitutionIdentityCandidate",
    "InstitutionSignalCandidate",
    "InstitutionSignalCategory",
    "InstitutionSourceType",
    "InstitutionVerificationNote",
    "JobAlioAttachment",
    "JobAlioDetail",
    "JobAlioSearchResult",
    "JobAlioStep",
    "JobAlioSummary",
    "JobFitEvidenceSource",
    "JobFitEvidenceType",
    "JobFitInstitutionSignal",
    "JobFitPreparationItem",
    "JobFitPreparationReport",
    "JobFitVerificationNote",
    "KsaCandidate",
    "KsaCategory",
    "NcsAttachmentCandidate",
    "NcsCodeMapping",
    "NcsEvidenceReference",
    "NcsEvidenceType",
    "NcsMappingInput",
    "NcsVerificationNote",
    "PreparationPriority",
]
